---
- hosts: all

  tasks:

    # run

    - name: Install postgresql
      apt: pkg=postgresql
      sudo: yes
      tags: run

    - name: Install java
      apt: pkg=openjdk-7-jre
      sudo: yes
      tags: run

    - name: Install tomcat
      apt: pkg=tomcat6
      sudo: yes
      tags: run

    - name: Install tomcat native
      apt: pkg=libtcnative-1
      sudo: yes
      tags: run

    - name: Install solr-tomcat
      apt: pkg=solr-tomcat
      sudo: yes
      tags: run

    - name: Install apache
      apt: pkg=apache2
      sudo: yes
      tags: run
      notify:
      - Generate SSL certificate
      - Setup VirtualHost
      - Enable VirtualHost
      - Install Apache module
      - Restart apache

    # manage

    - name: Install phppgadmin
      apt: pkg=phppgadmin
      sudo: yes
      tags: manage

    - name: Install tomcat6-admin
      apt: pkg=tomcat6-admin
      sudo: yes
      tags: manage

    # development

    - name: Install maven
      apt: pkg=maven2
      sudo: yes
      tags: development

    - name: Install git
      apt: pkg=git-core
      sudo: yes
      tags: development

    - name: Install avahi
      apt: pkg=avahi-daemon
      sudo: yes
      tags: development

  handlers:

    - name: Generate SSL certificate
      command: openssl req -new -nodes -x509 -subj "/C=AU/ST=Victoria/L=Selby/O=IT/CN=vagrant-bookmate.local" -days 3650 -keyout /etc/ssl/private/Qualis.key -out /etc/ssl/certs/Qualis.crt -extensions v3_ca creates=/etc/ssl/certs/Qualis.crt
      sudo: yes

    - name: Setup VirtualHost
      copy: src=resource/template/virtualhost dest=/etc/apache2/sites-available/qualis owner=www-data group=www-data
      sudo: yes

    - name: Enable VirtualHost
      file: src=/etc/apache2/sites-available/qualis dest=/etc/apache2/sites-enabled/qualis state=link owner=www-data group=www-data
      sudo: yes

    - name: Install Apache module
      apache2_module: state=present name={{item}}
      with_items:
        - ssl
        - proxy_http
      sudo: yes

    - name: Restart apache
      service: name=apache2 state=restarted
      sudo: yes
