---
- hosts: all

  tasks:

    - include: ../environment-core/provisioning/core.yml
    - include: ../environment-sproutcore/provisioning/sproutcore.yml
    - include: ../environment-apache/provisioning/apache.yml
    - include: ../environment-postgresql/provisioning/postgresql.yml
    - include: ../environment-tomcat/provisioning/tomcat.yml
    - include: BookMate.yml

  handlers:

    - include: ../environment-tomcat/provisioning/tomcat-handler.yml
    - include: ../environment-postgresql/provisioning/postgresql-handler.yml
    - include: ../environment-apache/provisioning/apache-handler.yml
