---
- hosts: all

  tasks:

    - include: ../environment-sproutcore/provisioning/sproutcore.yml
    - include: ../environment-apache/provisioning/apache.yml
    - include: ../environment-postgresql/provisioning/postgresql.yml
    - include: ../environment-tomcat/provisioning/tomcat.yml

    # requirements for postgresql_db ansible module

    - name: postgresql_db ansible module requirements
      apt: pkg={{ item }}
      sudo: yes
      with_items:
      - libpq-dev
      - python-psycopg2

    # run

    - name: Setup databases
      postgresql_db: name={{ item }}
      sudo: yes
      sudo_user: postgres
      with_items:
        - book_mate
        - book_mate_upgrade
        - book_mate_create

    - name: Install solr-tomcat
      apt: pkg=solr-tomcat
      sudo: yes
      tags: run

    - name: Create BookMate document root
      file: path=/BookMate/browser state=directory owner=www-data group=www-data
      sudo: yes

    - name: Add placeholder .html
      copy: src=resource/placeholder.html dest=/BookMate/browser/index.html owner=www-data group=www-data
      sudo: yes

    - name: Setup VirtualHost
      copy: src=resource/virtualhost dest=/etc/apache2/sites-available/qualis.conf owner=www-data group=www-data
      sudo: yes

    - name: Enable VirtualHost
      shell: a2ensite qualis
      sudo: yes
      notify:
      - Restart apache

    # development

    - name: Install maven
      apt: pkg=maven2
      sudo: yes
      tags: development

    - name: Install git
      apt: pkg=git-core
      sudo: yes
      tags: development

    - name: Install avahi
      apt: pkg=avahi-daemon
      sudo: yes
      tags: development

  handlers:

    - include: ../environment-tomcat/provisioning/tomcat-handler.yml
    - include: ../environment-postgresql/provisioning/postgresql-handler.yml
    - include: ../environment-apache/provisioning/apache-handler.yml
